apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3quq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-3quq@sha256:e924151ce31746eb4ec145d82b62b7d71634d277ae23a5884dc3b7bdf4ca4ba5
        name: my-nodejs
        resources: {}
status: {}
